-- 초기화용 테이블 날리기 .sql
DROP TABLE GAME_SESSION
DROP TABLE PLAYER_ITEM_DISPLAY;
DROP TABLE CUSTOMER_HIDDEN_DISCOVERED IN ;
DROP TABLE DEAL_RECORD;
DROP TABLE EXISTING_ITEM;
DROP TABLE ITEM_CATALOG;
DROP TABLE LOAN;
DROP TABLE EXISTING_NEWS;
DROP TABLE NEWS_CATALOG;
DROP TABLE CUSTOMER;
DROP TABLE PLAYER;
DROP TABLE ITEM_CATEGORY;

DROP TABLE ITEM_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE PLAYER CASCADE CONSTRAINTS;
DROP TABLE GAME_SESSION CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE ITEM_CATALOG CASCADE CONSTRAINTS;
DROP TABLE EXISTING_ITEM CASCADE CONSTRAINTS;
DROP TABLE DEAL_RECORD CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER_HIDDEN_DISCOVERED_IN_GAME_SESSION CASCADE CONSTRAINTS;
DROP TABLE GAME_SESSION_ITEM_DISPLAY CASCADE CONSTRAINTS;
DROP TABLE NEWS_CATALOG CASCADE CONSTRAINTS;
DROP TABLE EXISTING_NEWS CASCADE CONSTRAINTS;
